# Python CI Workflow
#
# Optimized for self-hosted Synology runners with resource constraints.
# Features:
# - Dependency caching (pip/poetry/pipenv)
# - Virtual environment management
# - Lint → Test → Build pipeline
# - Code coverage and quality checks
#
# Copy this to: .github/workflows/ci.yml in your repository

name: Python CI

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

# Per-workflow, per-branch concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build and Test
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 20

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v6

      # Step 2: Setup Python with caching
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'  # Or '3.10', '3.12', etc.
          cache: 'pip'  # Automatically caches pip dependencies

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If you have dev dependencies:
          # pip install -r requirements-dev.txt

      # Step 4: Lint code (flake8, black, etc.)
      - name: Lint with flake8
        run: |
          pip install flake8
          # Stop build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true

      # Step 5: Check code formatting (black)
      - name: Check code formatting
        run: |
          pip install black
          black --check .
        continue-on-error: true

      # Step 6: Type checking (mypy)
      - name: Type check with mypy
        run: |
          pip install mypy
          mypy . --ignore-missing-imports
        continue-on-error: true

      # Step 7: Run tests with pytest
      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=. --cov-report=xml --cov-report=term
        env:
          # Set environment for tests
          PYTHONPATH: ${{ github.workspace }}

      # Step 8: Upload coverage (optional)
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     file: ./coverage.xml
      #     fail_ci_if_error: false

      # Step 9: Build package (if creating distribution)
      - name: Build package
        run: |
          pip install build
          python -m build
        # Only if you're building a package

      # Step 10: Upload artifacts
      - name: Upload dist artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          retention-days: 7

## Customization Options

### Using Poetry Package Manager
#
# - name: Setup Python
#   uses: actions/setup-python@v6
#   with:
#     python-version: '3.11'
#     cache: 'poetry'
#
# - name: Install Poetry
#   run: |
#     curl -sSL https://install.python-poetry.org | python3 -
#     export PATH="$HOME/.local/bin:$PATH"
#
# - name: Install dependencies
#   run: poetry install --no-interaction
#
# - name: Run tests
#   run: poetry run pytest

### Using Pipenv
#
# - name: Setup Python
#   uses: actions/setup-python@v6
#   with:
#     python-version: '3.11'
#     cache: 'pipenv'
#
# - name: Install Pipenv
#   run: pip install pipenv
#
# - name: Install dependencies
#   run: pipenv install --dev
#
# - name: Run tests
#   run: pipenv run pytest

### Using Virtual Environment Manually
#
# - name: Create virtual environment
#   run: |
#     python -m venv venv
#     source venv/bin/activate
#     pip install -r requirements.txt
#
# - name: Run tests
#   run: |
#     source venv/bin/activate
#     pytest

### Multiple Python Versions (Matrix Strategy)
#
# jobs:
#   ci:
#     strategy:
#       matrix:
#         python-version: ['3.9', '3.10', '3.11', '3.12']
#     steps:
#       - uses: actions/setup-python@v6
#         with:
#           python-version: ${{ matrix.python-version }}
#
# Note: Creates multiple jobs - use carefully on single runner!
# Better: Test only your target version

### Django Project Example
#
# - name: Install dependencies
#   run: |
#     pip install -r requirements.txt
#     pip install pytest-django
#
# - name: Run migrations
#   run: python manage.py migrate
#   env:
#     DATABASE_URL: sqlite:///test.db
#
# - name: Run tests
#   run: pytest
#   env:
#     DJANGO_SETTINGS_MODULE: myproject.settings
#     DATABASE_URL: sqlite:///test.db

### FastAPI Project Example
#
# - name: Install dependencies
#   run: |
#     pip install -r requirements.txt
#     pip install pytest httpx
#
# - name: Run tests
#   run: pytest tests/ -v
#
# - name: Start server and test (optional)
#   run: |
#     uvicorn main:app --host 0.0.0.0 --port 8000 &
#     sleep 5
#     curl http://localhost:8000/health
#     kill %1

### Flask Project Example
#
# - name: Install dependencies
#   run: |
#     pip install -r requirements.txt
#     pip install pytest flask-testing
#
# - name: Run tests
#   run: pytest
#   env:
#     FLASK_ENV: testing

### Data Science / Jupyter Notebooks
#
# - name: Install dependencies
#   run: |
#     pip install -r requirements.txt
#     pip install jupyter nbconvert
#
# - name: Test notebooks
#   run: |
#     jupyter nbconvert --to notebook --execute notebooks/*.ipynb
#
# - name: Convert to HTML
#   run: |
#     jupyter nbconvert --to html notebooks/*.ipynb

### Additional Code Quality Tools
#
# - name: Security check with bandit
#   run: |
#     pip install bandit
#     bandit -r . -f json -o bandit-report.json
#   continue-on-error: true
#
# - name: Check dependencies for vulnerabilities
#   run: |
#     pip install safety
#     safety check --json
#   continue-on-error: true
#
# - name: Complexity check with radon
#   run: |
#     pip install radon
#     radon cc . -a -nb
#   continue-on-error: true

### Parallel Test Execution (pytest-xdist)
#
# - name: Run tests in parallel
#   run: |
#     pip install pytest-xdist
#     # Run with 2 workers (adjust based on CPU)
#     pytest -n 2
#     # Or auto-detect CPUs:
#     # pytest -n auto

### Caching Additional Directories
#
# - name: Cache hypothesis examples
#   uses: actions/cache@v4
#   with:
#     path: .hypothesis
#     key: hypothesis-${{ hashFiles('tests/**/*.py') }}
#
# - name: Cache mypy cache
#   uses: actions/cache@v4
#   with:
#     path: .mypy_cache
#     key: mypy-${{ hashFiles('**/*.py') }}

### Resource Optimization
#
# For large test suites or memory-intensive operations:
#
# - name: Run tests with limited resources
#   run: |
#     # Limit parallel test workers
#     pytest -n 1
#     # Or disable parallelism entirely
#     pytest --workers 0
#   env:
#     # Limit Python memory
#     PYTHONMALLOC: malloc

### Deploy to PyPI (Example)
#
# deploy:
#   runs-on: [self-hosted, Linux, X64]
#   needs: ci
#   if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
#   steps:
#     - uses: actions/checkout@v6
#     - uses: actions/setup-python@v6
#       with:
#         python-version: '3.11'
#
#     - name: Build package
#       run: |
#         pip install build twine
#         python -m build
#
#     - name: Publish to PyPI
#       env:
#         TWINE_USERNAME: __token__
#         TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#       run: |
#         twine upload dist/*

## Troubleshooting

### Import Errors
# Ensure PYTHONPATH includes your source directory:
# env:
#   PYTHONPATH: ${{ github.workspace }}/src

### Package Installation Fails
# Try upgrading pip first:
# python -m pip install --upgrade pip setuptools wheel

### Tests Can't Find Modules
# Install package in editable mode:
# pip install -e .

### Slow pip install
# Use pip cache (automatic with actions/setup-python)
# Or use --no-deps if dependencies are already installed

### Pytest Collection Errors
# Ensure pytest.ini or pyproject.toml is configured:
# [tool.pytest.ini_options]
# testpaths = ["tests"]
# python_files = ["test_*.py", "*_test.py"]
